// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameShop = "shops"

// Shop mapped from table <shops>
type Shop struct {
	ID        int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null" json:"created_at"`                 // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`                 // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`                          // 删除时间
	Mid       int64          `gorm:"column:mid;type:bigint(20) unsigned;not null" json:"mid"`                    // 商户
	Status    int32          `gorm:"column:status;type:tinyint(3) unsigned;not null" json:"status"`              // 状态 0=禁用,1=暂停营业(商家),2=打烊(系统),3=正常
	Name      string         `gorm:"column:name;type:varchar(32);not null" json:"name"`                          // 店铺名称
	Province  string         `gorm:"column:province;type:varchar(32);not null" json:"province"`                  // 省
	City      string         `gorm:"column:city;type:varchar(32);not null" json:"city"`                          // 市
	Area      string         `gorm:"column:area;type:varchar(32);not null" json:"area"`                          // 区
	Street    string         `gorm:"column:street;type:varchar(32);not null" json:"street"`                      // 街道地址
	Contact   string         `gorm:"column:contact;type:varchar(32);not null" json:"contact"`                    // 联系人
	Tel       string         `gorm:"column:tel;type:varchar(32);not null" json:"tel"`                            // 商家电话
	StartTime *time.Time     `gorm:"column:start_time;type:time;not null;default:00:00:00" json:"start_time"`    // 开始营业时间
	EndTime   *time.Time     `gorm:"column:end_time;type:time;not null;default:00:00:00" json:"end_time"`        // 结束营业时间
	Lat       string         `gorm:"column:lat;type:varchar(50);not null" json:"lat"`                            // 纬度
	Lng       string         `gorm:"column:lng;type:varchar(50);not null" json:"lng"`                            // 经度
	Notice    string         `gorm:"column:notice;type:varchar(255);not null" json:"notice"`                     // 公告
}

// TableName Shop's table name
func (*Shop) TableName() string {
	return TableNameShop
}
