// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameShopGoods = "shop_goods"

// ShopGoods mapped from table <shop_goods>
type ShopGoods struct {
	ID           int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"` // ID
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;not null" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	Mid          int64          `gorm:"column:mid;type:bigint(20) unsigned;not null" json:"mid"`                         // 商户
	ShopID       int64          `gorm:"column:shop_id;type:bigint(20) unsigned;not null" json:"shop_id"`                 // 门店
	CategoryID   int64          `gorm:"column:category_id;type:bigint(20) unsigned;not null" json:"category_id"`         // 配件类别
	AttributeIds string         `gorm:"column:attribute_ids;type:varchar(1024);not null" json:"attribute_ids"`           // 属性
	Name         string         `gorm:"column:name;type:varchar(50);not null" json:"name"`                               // 名称
	Pinyin       string         `gorm:"column:pinyin;type:varchar(128);not null" json:"pinyin"`                          // 拼音
	Images       string         `gorm:"column:images;type:varchar(1024);not null" json:"images"`                         // 图片
	UnitName     string         `gorm:"column:unit_name;type:varchar(10);not null" json:"unit_name"`                     // 单位
	Num          *float64       `gorm:"column:num;type:decimal(10,2) unsigned;not null;default:0.00" json:"num"`         // 库存数量
	Price        *float64       `gorm:"column:price;type:decimal(10,2) unsigned;not null;default:0.00" json:"price"`     // 销售价格
	Sn           string         `gorm:"column:sn;type:varchar(64);not null" json:"sn"`                                   // 编号
	UpdateBy     int64          `gorm:"column:update_by;type:bigint(20) unsigned;not null" json:"update_by"`             // 操作人
	MinNum       *float64       `gorm:"column:min_num;type:decimal(10,2) unsigned;not null;default:0.00" json:"min_num"` // 最少库存量
	Shops        Shop           `gorm:"foreignKey:shop_id" json:"shops"`
}

// TableName ShopGoods's table name
func (*ShopGoods) TableName() string {
	return TableNameShopGoods
}
